// flow-typed signature: 59bb8a07810d755f8e47c407708242af
// flow-typed version: <<STUB>>/gatsby-plugin-prefetch-google-fonts_v^1.4.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-prefetch-google-fonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-prefetch-google-fonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-prefetch-google-fonts/download-css' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-prefetch-google-fonts/download-fonts' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-prefetch-google-fonts/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-prefetch-google-fonts/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-prefetch-google-fonts/merge-css' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-prefetch-google-fonts/download-css.js' {
  declare module.exports: $Exports<'gatsby-plugin-prefetch-google-fonts/download-css'>;
}
declare module 'gatsby-plugin-prefetch-google-fonts/download-fonts.js' {
  declare module.exports: $Exports<'gatsby-plugin-prefetch-google-fonts/download-fonts'>;
}
declare module 'gatsby-plugin-prefetch-google-fonts/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-prefetch-google-fonts/gatsby-node'>;
}
declare module 'gatsby-plugin-prefetch-google-fonts/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-prefetch-google-fonts/gatsby-ssr'>;
}
declare module 'gatsby-plugin-prefetch-google-fonts/merge-css.js' {
  declare module.exports: $Exports<'gatsby-plugin-prefetch-google-fonts/merge-css'>;
}
