// flow-typed signature: 61ba6fa0eac4662516361ddb84589bf6
// flow-typed version: <<STUB>>/gatsby-background-image_v^0.8.9/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-background-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-background-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-background-image/BackgroundUtils' {
  declare module.exports: any;
}

declare module 'gatsby-background-image/HelperUtils' {
  declare module.exports: any;
}

declare module 'gatsby-background-image/ImageUtils' {
  declare module.exports: any;
}

declare module 'gatsby-background-image/IntersectionObserverUtils' {
  declare module.exports: any;
}

declare module 'gatsby-background-image/StyleUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-background-image/BackgroundUtils.js' {
  declare module.exports: $Exports<'gatsby-background-image/BackgroundUtils'>;
}
declare module 'gatsby-background-image/HelperUtils.js' {
  declare module.exports: $Exports<'gatsby-background-image/HelperUtils'>;
}
declare module 'gatsby-background-image/ImageUtils.js' {
  declare module.exports: $Exports<'gatsby-background-image/ImageUtils'>;
}
declare module 'gatsby-background-image/index' {
  declare module.exports: $Exports<'gatsby-background-image'>;
}
declare module 'gatsby-background-image/index.js' {
  declare module.exports: $Exports<'gatsby-background-image'>;
}
declare module 'gatsby-background-image/IntersectionObserverUtils.js' {
  declare module.exports: $Exports<'gatsby-background-image/IntersectionObserverUtils'>;
}
declare module 'gatsby-background-image/StyleUtils.js' {
  declare module.exports: $Exports<'gatsby-background-image/StyleUtils'>;
}
