// flow-typed signature: 0cef7078ccddf889de99cc94d9ebcead
// flow-typed version: <<STUB>>/intersection-observer_v^0.7.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intersection-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intersection-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intersection-observer/intersection-observer-test' {
  declare module.exports: any;
}

declare module 'intersection-observer/intersection-observer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intersection-observer/intersection-observer-test.js' {
  declare module.exports: $Exports<'intersection-observer/intersection-observer-test'>;
}
declare module 'intersection-observer/intersection-observer.js' {
  declare module.exports: $Exports<'intersection-observer/intersection-observer'>;
}
