// flow-typed signature: b70e7cd4204736f97dff02ce62a45a5b
// flow-typed version: <<STUB>>/normalize.css_v^8.0.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
