// flow-typed signature: 53f8060a73b13cdb047682aeb5de4e9b
// flow-typed version: <<STUB>>/react-typing-animation_v^1.6.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-typing-animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-typing-animation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-typing-animation/dist/Backspace' {
  declare module.exports: any;
}

declare module 'react-typing-animation/dist/Cursor' {
  declare module.exports: any;
}

declare module 'react-typing-animation/dist/Delay' {
  declare module.exports: any;
}

declare module 'react-typing-animation/dist' {
  declare module.exports: any;
}

declare module 'react-typing-animation/dist/Reset' {
  declare module.exports: any;
}

declare module 'react-typing-animation/dist/Speed' {
  declare module.exports: any;
}

declare module 'react-typing-animation/dist/Typing' {
  declare module.exports: any;
}

declare module 'react-typing-animation/dist/utils' {
  declare module.exports: any;
}

declare module 'react-typing-animation/example/App' {
  declare module.exports: any;
}

declare module 'react-typing-animation/example/build/main' {
  declare module.exports: any;
}

declare module 'react-typing-animation/example' {
  declare module.exports: any;
}

declare module 'react-typing-animation/example/postcss.config' {
  declare module.exports: any;
}

declare module 'react-typing-animation/example/webpack-dev-server' {
  declare module.exports: any;
}

declare module 'react-typing-animation/example/webpack.config' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src/Backspace' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src/Cursor' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src/Delay' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src/Reset' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src/Speed' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src/Typing' {
  declare module.exports: any;
}

declare module 'react-typing-animation/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-typing-animation/dist/Backspace.js' {
  declare module.exports: $Exports<'react-typing-animation/dist/Backspace'>;
}
declare module 'react-typing-animation/dist/Cursor.js' {
  declare module.exports: $Exports<'react-typing-animation/dist/Cursor'>;
}
declare module 'react-typing-animation/dist/Delay.js' {
  declare module.exports: $Exports<'react-typing-animation/dist/Delay'>;
}
declare module 'react-typing-animation/dist/index' {
  declare module.exports: $Exports<'react-typing-animation/dist'>;
}
declare module 'react-typing-animation/dist/index.js' {
  declare module.exports: $Exports<'react-typing-animation/dist'>;
}
declare module 'react-typing-animation/dist/Reset.js' {
  declare module.exports: $Exports<'react-typing-animation/dist/Reset'>;
}
declare module 'react-typing-animation/dist/Speed.js' {
  declare module.exports: $Exports<'react-typing-animation/dist/Speed'>;
}
declare module 'react-typing-animation/dist/Typing.js' {
  declare module.exports: $Exports<'react-typing-animation/dist/Typing'>;
}
declare module 'react-typing-animation/dist/utils.js' {
  declare module.exports: $Exports<'react-typing-animation/dist/utils'>;
}
declare module 'react-typing-animation/example/App.js' {
  declare module.exports: $Exports<'react-typing-animation/example/App'>;
}
declare module 'react-typing-animation/example/build/main.js' {
  declare module.exports: $Exports<'react-typing-animation/example/build/main'>;
}
declare module 'react-typing-animation/example/index' {
  declare module.exports: $Exports<'react-typing-animation/example'>;
}
declare module 'react-typing-animation/example/index.js' {
  declare module.exports: $Exports<'react-typing-animation/example'>;
}
declare module 'react-typing-animation/example/postcss.config.js' {
  declare module.exports: $Exports<'react-typing-animation/example/postcss.config'>;
}
declare module 'react-typing-animation/example/webpack-dev-server.js' {
  declare module.exports: $Exports<'react-typing-animation/example/webpack-dev-server'>;
}
declare module 'react-typing-animation/example/webpack.config.js' {
  declare module.exports: $Exports<'react-typing-animation/example/webpack.config'>;
}
declare module 'react-typing-animation/src/Backspace.js' {
  declare module.exports: $Exports<'react-typing-animation/src/Backspace'>;
}
declare module 'react-typing-animation/src/Cursor.js' {
  declare module.exports: $Exports<'react-typing-animation/src/Cursor'>;
}
declare module 'react-typing-animation/src/Delay.js' {
  declare module.exports: $Exports<'react-typing-animation/src/Delay'>;
}
declare module 'react-typing-animation/src/index' {
  declare module.exports: $Exports<'react-typing-animation/src'>;
}
declare module 'react-typing-animation/src/index.js' {
  declare module.exports: $Exports<'react-typing-animation/src'>;
}
declare module 'react-typing-animation/src/Reset.js' {
  declare module.exports: $Exports<'react-typing-animation/src/Reset'>;
}
declare module 'react-typing-animation/src/Speed.js' {
  declare module.exports: $Exports<'react-typing-animation/src/Speed'>;
}
declare module 'react-typing-animation/src/Typing.js' {
  declare module.exports: $Exports<'react-typing-animation/src/Typing'>;
}
declare module 'react-typing-animation/src/utils.js' {
  declare module.exports: $Exports<'react-typing-animation/src/utils'>;
}
