// flow-typed signature: 6d3049665ed8eb04ba13101a8ff4d4d5
// flow-typed version: <<STUB>>/@fika/gatsby-source-cockpit_v^1.1.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fika/gatsby-source-cockpit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fika/gatsby-source-cockpit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fika/gatsby-source-cockpit/extend-node-type' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/gatsby-node' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/CockpitService' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/CollectionItemNodeFactory' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/constants' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/FileNodeFactory' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/helpers' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/LayoutNodeFactory' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/MarkdownNodeFactory' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/ObjectNodeFactory' {
  declare module.exports: any;
}

declare module '@fika/gatsby-source-cockpit/src/SingletonItemNodeFactory' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fika/gatsby-source-cockpit/extend-node-type.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/extend-node-type'>;
}
declare module '@fika/gatsby-source-cockpit/gatsby-node.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/gatsby-node'>;
}
declare module '@fika/gatsby-source-cockpit/src/CockpitService.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/CockpitService'>;
}
declare module '@fika/gatsby-source-cockpit/src/CollectionItemNodeFactory.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/CollectionItemNodeFactory'>;
}
declare module '@fika/gatsby-source-cockpit/src/constants.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/constants'>;
}
declare module '@fika/gatsby-source-cockpit/src/FileNodeFactory.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/FileNodeFactory'>;
}
declare module '@fika/gatsby-source-cockpit/src/helpers.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/helpers'>;
}
declare module '@fika/gatsby-source-cockpit/src/LayoutNodeFactory.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/LayoutNodeFactory'>;
}
declare module '@fika/gatsby-source-cockpit/src/MarkdownNodeFactory.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/MarkdownNodeFactory'>;
}
declare module '@fika/gatsby-source-cockpit/src/ObjectNodeFactory.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/ObjectNodeFactory'>;
}
declare module '@fika/gatsby-source-cockpit/src/SingletonItemNodeFactory.js' {
  declare module.exports: $Exports<'@fika/gatsby-source-cockpit/src/SingletonItemNodeFactory'>;
}
